package getdns

// #include <getdns/getdns.h>
import "C"

// getdns result codes.
const (
    RETURN_GOOD                        = C.GETDNS_RETURN_GOOD
    RETURN_GENERIC_ERROR               = C.GETDNS_RETURN_GENERIC_ERROR
    RETURN_BAD_DOMAIN_NAME             = C.GETDNS_RETURN_BAD_DOMAIN_NAME
    RETURN_BAD_CONTEXT                 = C.GETDNS_RETURN_BAD_CONTEXT
    RETURN_UPDATE_FAIL                 = C.GETDNS_RETURN_CONTEXT_UPDATE_FAIL
    RETURN_UNKNOWN_TRANSACTION         = C.GETDNS_RETURN_UNKNOWN_TRANSACTION
    RETURN_NO_SUCH_LIST_ITEM           = C.GETDNS_RETURN_NO_SUCH_LIST_ITEM
    RETURN_NO_SUCH_DICT_NAME           = C.GETDNS_RETURN_NO_SUCH_DICT_NAME
    RETURN_WRONG_TYPE_REQUESTED        = C.GETDNS_RETURN_WRONG_TYPE_REQUESTED
    RETURN_NO_SUCH_EXTENSION           = C.GETDNS_RETURN_NO_SUCH_EXTENSION
    RETURN_EXTENSION_MISFORMAT         = C.GETDNS_RETURN_EXTENSION_MISFORMAT
    RETURN_DNSSEC_WITH_STUB_DISALLOWED = C.GETDNS_RETURN_DNSSEC_WITH_STUB_DISALLOWED
    RETURN_MEMORY_ERROR                = C.GETDNS_RETURN_MEMORY_ERROR
    RETURN_INVALID_PARAMTER            = C.GETDNS_RETURN_INVALID_PARAMETER
    RETURN_NO_IMPLEMENTED              = C.GETDNS_RETURN_NOT_IMPLEMENTED
)

// response status codes
const (
    RESPSTATUS_GOOD                 = C.GETDNS_RESPSTATUS_GOOD
    RESPSTATUS_NO_NAME              = C.GETDNS_RESPSTATUS_NO_NAME
    RESPSTATUS_ALL_TIMEOUT          = C.GETDNS_RESPSTATUS_ALL_TIMEOUT
    RESPSTATUS_NO_SECURE_ANSWERS    = C.GETDNS_RESPSTATUS_NO_SECURE_ANSWERS
    RESPSTATUS_NO_ALL_BOGUS_ANSWERS = C.GETDNS_RESPSTATUS_ALL_BOGUS_ANSWERS
)

// response anwer types
const (
    NAMETYPE_DNS  = C.GETDNS_NAMETYPE_DNS
    NAMETYPE_WINS = C.GETDNS_NAMETYPE_WINS
)

// extension request values
const (
    EXTENSION_TRUE  = C.GETDNS_EXTENSION_TRUE
    EXTENSION_FALSE = C.GETDNS_EXTENSION_FALSE
)

// extension response values
const (
    BAD_DNS_CNAME_IN_TARGET               = C.GETDNS_BAD_DNS_CNAME_IN_TARGET
    BAD_DNS_ALL_NUMERIC_LABEL             = C.GETDNS_BAD_DNS_ALL_NUMERIC_LABEL
    BAD_DNS_CNAME_RETURNED_FOR_OTHER_TYPE = C.GETDNS_BAD_DNS_CNAME_RETURNED_FOR_OTHER_TYPE
)
